# -*- coding: utf-8 -*-
"""board.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1oEJ5nJ9wVlvLY7jzC4L4eNBeYJDDxxeV
"""

board = [["-","-","-"], ["-","-","-"],["-","-","-"]]


def print_board():
  for i in board:
    print(i)
  print("Board printed.")
  pass

print_board()